name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    name: RSpec (${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3.0']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec

  steep:
    name: Steep (${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3.0']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install RBS collection
        run: bundle exec rbs collection install
      - name: Run Steep
        run: bundle exec steep check

  standardrb:
    name: StandardRB (${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3.0']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run StandardRB
        run: bundle exec standardrb

  ruby_audit:
    name: Ruby Audit (${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3.0']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update Advisory DB and Audit
        run: |
          bundle exec bundle audit update
          bundle exec bundle audit check
